In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


In [4]:
a = torch.empty(2,3)
print(a)

tensor([[1.6630e+22, 2.6539e-09, 8.3154e-07],
        [1.4580e-19, 1.1495e+24, 3.0881e+29]])


In [5]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

Manual seed gives same random values

In [7]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [8]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [10]:
x = torch.tensor([[1,2,3],[4,5,6]])
print("shape of x ->", x.shape)
print("number of dimensions ->", x.ndim)

shape of x -> torch.Size([2, 3])
number of dimensions -> 2


In [11]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [12]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Mathematical operations

In [17]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print("a ->", a)
print("b ->", b)

a -> tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])
b -> tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])


In [18]:

a + b
a - b
a * b
a / b
a ** b
a % b

tensor([[0.0706, 0.2767, 0.4440],
        [0.2063, 0.7445, 0.0657]])

In [19]:
c = torch.tensor([1, -2, 3, -4])

In [21]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [22]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [23]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [24]:
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

In [25]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 7., 3.],
        [9., 4., 0.]])

In [26]:
torch.sum(e)
torch.sum(e, dim=0)

tensor([14., 11.,  3.])

In [27]:
torch.prod(e)
torch.median(e)


tensor(4.)

In [28]:
torch.argmin(e)

tensor(5)

 Matrix operations

In [29]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 5],
        [9, 9, 7]])
tensor([[5, 9],
        [8, 9],
        [7, 9]])


In [30]:
torch.matmul(f, g)

tensor([[116, 153],
        [166, 225]])

In [31]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

torch.dot(vector1, vector2)

tensor(11)

In [33]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[2., 6., 7.],
        [7., 8., 3.],
        [6., 1., 5.]])

In [34]:
torch.det(h)

tensor(-315.)

In [35]:
torch.inverse(h)

tensor([[-0.1175,  0.0730,  0.1206],
        [ 0.0540,  0.1016, -0.1365],
        [ 0.1302, -0.1079,  0.0825]])

Special functions

In [36]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 0., 4.],
        [3., 8., 8.]])

In [37]:

torch.log(k)

tensor([[1.6094,   -inf, 1.3863],
        [1.0986, 2.0794, 2.0794]])

In [39]:
torch.softmax(k, dim=0)

tensor([[8.8080e-01, 3.3535e-04, 1.7986e-02],
        [1.1920e-01, 9.9966e-01, 9.8201e-01]])

Tensor operation on GPU

In [42]:
a = torch.rand((2,3),device="cuda")
a

tensor([[0.1638, 0.9768, 0.8114],
        [0.9476, 0.5558, 0.6393]], device='cuda:0')

In [43]:
import torch
import time

x = torch.randn(10000, 10000)

start = time.time()
y = x * x
print("CPU Time:", time.time() - start)

# GPU timing
device = "cuda" if torch.cuda.is_available() else "cpu"

x_gpu = x.to(device)

torch.cuda.synchronize()  

start = time.time()
y_gpu = x_gpu * x_gpu

torch.cuda.synchronize()   
print("GPU Time:", time.time() - start)

CPU Time: 0.1843249797821045
GPU Time: 0.003988027572631836


Reshaping Tensors

In [44]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(x.shape)

torch.Size([2, 3])


In [45]:
y = x.reshape(3, 2)

print(y)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [46]:
x.flatten()

tensor([1, 2, 3, 4, 5, 6])

In [47]:
c = torch.rand(226,226,3)

c = c.unsqueeze(0)
print(c.shape)

torch.Size([1, 226, 226, 3])


In [48]:
d = torch.rand(1, 226, 226, 3)
d = d.squeeze(0)
print(d.shape)

torch.Size([226, 226, 3])
