In [ ]:
import torch

print(torch.cuda.is_available())   
print(torch.cuda.get_device_name(0)) 

True
Tesla T4


In [2]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

Matrix multiplication of NUMPY

In [3]:
W = [[1, 1, 1],
     [1.5, 1.5, 1.5],
     [2, 2, 2]]

x = [[6],
     [7],
     [8]]

b_np = np.ones((3, 1))

# y=Wx+b

output = np.matmul(W,x) + b_np

# Print out the result
print("Output:\n", output)
print("Output shape:\n", output.shape)

Output:
 [[22. ]
 [32.5]
 [43. ]]
Output shape:
 (3, 1)


In [6]:
W_torch = torch.FloatTensor(W)

x_torch = torch.FloatTensor(x)

b_torch = torch.ones(3, 1)

output = torch.matmul(W_torch, x_torch) + b_torch

print("Output:\n", output)
print("Output dtype:\n", output.dtype)
print("Output shape:\n", output.shape)

Output:
 tensor([[22.0000],
        [32.5000],
        [43.0000]])
Output dtype:
 torch.float32
Output shape:
 torch.Size([3, 1])


Default Datatype is Flot but we can convert into int

In [5]:
W_torch = torch.FloatTensor(W).to(torch.int64)

x_torch = torch.FloatTensor(x).to(torch.int64)

b_torch = torch.ones(3, 1).to(torch.int64)

output = torch.matmul(W_torch, x_torch) + b_torch

print("Output:\n", output)
print("Output dtype:\n", output.dtype)
print("Output shape:\n", output.shape)

Output:
 tensor([[22],
        [22],
        [43]])
Output dtype:
 torch.int64
Output shape:
 torch.Size([3, 1])


conversion of Pytorch to numpy and visa versa

In [7]:
np_array = np.random.random((3, 4))
print("Numpy array:\n", np_array)

torch_tensor = torch.FloatTensor(np_array)
print("Pytorch tensor:\n", torch_tensor)

np_array2 = torch_tensor.numpy()
print("Numpy array:\n", np_array2)

Numpy array:
 [[0.87692887 0.52795792 0.25949624 0.08636725]
 [0.59898478 0.87584066 0.75114201 0.64756748]
 [0.004546   0.49994861 0.13714785 0.45376557]]
Pytorch tensor:
 tensor([[0.8769, 0.5280, 0.2595, 0.0864],
        [0.5990, 0.8758, 0.7511, 0.6476],
        [0.0045, 0.4999, 0.1371, 0.4538]])
Numpy array:
 [[0.87692887 0.5279579  0.25949624 0.08636725]
 [0.5989848  0.87584066 0.751142   0.64756745]
 [0.004546   0.49994862 0.13714784 0.45376557]]


In [8]:
y = torch.rand(4, 5)
print("Our 1D Tensor:\n",y)

print("\nScalar Multiplication:\n",y * 10)
print("Addition and Square:\n",(y + 1)**2)
print("Addition:\n",y + y)
print("Addition and division:\n",y / (y + 1))

print("\nPower and square root:\n",torch.sqrt(y**2))

print("\nY -\n Min:%.2f\n Max:%.2f\n Standard Deviation:%.2f\n Sum:%.2f" %(y.min(), y.max(), y.std(), y.sum()))

Our 1D Tensor:
 tensor([[0.2966, 0.7349, 0.9110, 0.8590, 0.0320],
        [0.7524, 0.2706, 0.9826, 0.9835, 0.3103],
        [0.7827, 0.5789, 0.1932, 0.5389, 0.6360],
        [0.9024, 0.6123, 0.9895, 0.9687, 0.3766]])

Scalar Multiplication:
 tensor([[2.9660, 7.3493, 9.1104, 8.5902, 0.3200],
        [7.5237, 2.7062, 9.8264, 9.8347, 3.1027],
        [7.8270, 5.7894, 1.9322, 5.3891, 6.3602],
        [9.0238, 6.1233, 9.8955, 9.6870, 3.7661]])
Addition and Square:
 tensor([[1.6812, 3.0100, 3.6521, 3.4560, 1.0650],
        [3.0708, 1.6145, 3.9309, 3.9342, 1.7168],
        [3.1780, 2.4930, 1.4238, 2.3683, 2.6766],
        [3.6191, 2.5996, 3.9583, 3.8758, 1.8950]])
Addition:
 tensor([[0.5932, 1.4699, 1.8221, 1.7180, 0.0640],
        [1.5047, 0.5412, 1.9653, 1.9669, 0.6205],
        [1.5654, 1.1579, 0.3864, 1.0778, 1.2720],
        [1.8048, 1.2247, 1.9791, 1.9374, 0.7532]])
Addition and division:
 tensor([[0.2288, 0.4236, 0.4767, 0.4621, 0.0310],
        [0.4293, 0.2130, 0.4956, 0.4958, 0.2368]

torch.matmul() - General-purpose matrix multiplication (1-D,2-D)

torch.bmm() - batch matrix multiplication (3-D)

In [ ]:
tensor_1 = torch.rand(3,3,3)
tensor_2 = torch.rand(3,3,3)

print("Tensor 1:\n",tensor_1)
print("Tensor 2:\n",tensor_2)

print("Addition:\n",tensor_1 + tensor_2)

print("Batch Multiplication:\n", torch.bmm(tensor_1, tensor_2))

Tensor 1:
 tensor([[[0.1046, 0.6120, 0.4195],
         [0.9971, 0.4801, 0.0363],
         [0.0830, 0.0122, 0.8298]],

        [[0.9627, 0.7152, 0.9788],
         [0.0127, 0.9439, 0.7995],
         [0.9686, 0.6001, 0.5236]],

        [[0.9195, 0.3997, 0.0293],
         [0.4459, 0.4453, 0.0693],
         [0.0470, 0.0720, 0.6190]]])
Tensor 2:
 tensor([[[0.6080, 0.4594, 0.2188],
         [0.1733, 0.5625, 0.6184],
         [0.9487, 0.3698, 0.3186]],

        [[0.8500, 0.6813, 0.9056],
         [0.2446, 0.8518, 0.4608],
         [0.1661, 0.7040, 0.6995]],

        [[0.3951, 0.4737, 0.3435],
         [0.4420, 0.4858, 0.3068],
         [0.5257, 0.3791, 0.9248]]])
Addition:
 tensor([[[0.7126, 1.0714, 0.6384],
         [1.1704, 1.0426, 0.6547],
         [1.0317, 0.3819, 1.1484]],

        [[1.8127, 1.3966, 1.8844],
         [0.2574, 1.7957, 1.2602],
         [1.1347, 1.3041, 1.2231]],

        [[1.3145, 0.8734, 0.3728],
         [0.8879, 0.9310, 0.3761],
         [0.5727, 0.4510, 1.5437]]])
Batc

In [12]:
print("The Tensor's shape is:", tensor_1.shape)

print("The Tensor's shape using size() is:", tensor_1.size())

print("There are %d elements in total:" % tensor_1.numel())

print("There are %d Dimensions" %(tensor_1.ndim))

print("Flattened Tensor:\n", tensor_1.flatten())

The Tensor's shape is: torch.Size([3, 3, 3])
The Tensor's shape using size() is: torch.Size([3, 3, 3])
There are 27 elements in total:
There are 3 Dimensions
Flattened Tensor:
 tensor([0.1046, 0.6120, 0.4195, 0.9971, 0.4801, 0.0363, 0.0830, 0.0122, 0.8298,
        0.9627, 0.7152, 0.9788, 0.0127, 0.9439, 0.7995, 0.9686, 0.6001, 0.5236,
        0.9195, 0.3997, 0.0293, 0.4459, 0.4453, 0.0693, 0.0470, 0.0720, 0.6190])


Broadcasting automatically makes tensors of different shapes compatible for operations like ADD,SUB,MULTI,DIV etc.

start from right to left

without broadcasting we need to do reshpaing and manually copying

In [13]:
tensor1 = torch.rand(1, 4, 3, 1)
tensor2 = torch.rand(3, 4, 1, 4)

print("Tensor 1 shape:\n", tensor1.shape)
print("Tensor 2 shape:\n", tensor2.shape)

tensor3 = tensor1 + tensor2

print("The resulting shape is:\n", tensor3.shape)

Tensor 1 shape:
 torch.Size([1, 4, 3, 1])
Tensor 2 shape:
 torch.Size([3, 4, 1, 4])
The resulting shape is:
 torch.Size([3, 4, 3, 4])


Autograd (Automatic Differentiation) 

Why Gradients Matter

Neural networks learn by updating weights.

To update weights, we need:
gradient of loss with respect to weights and Mathematically:

∂W
∂Loss
	​

Doing this manually for large networks is extremely difficult.

In [14]:
x = torch.FloatTensor([4])
x.requires_grad = True
w = torch.FloatTensor([2])
w.requires_grad = True
b = torch.FloatTensor([3])
b.requires_grad = True

# By performing a simple computation Pytorch will build a computational graph.
y = w * x + b   


y.backward()


print("Calculated Gradients") 
print("dy/dx", x.grad.item())    # x.grad = dy/dx = 2 
print("dy/dw", w.grad.item())    # w.grad = dy/dw = 4
print("dy/db", b.grad.item())   # b.grad = dy/db = 1  

Calculated Gradients
dy/dx 2.0
dy/dw 4.0
dy/db 1.0
