Neural Network architecture

In [1]:
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [2]:
features = torch.rand(10, 5)

model = Model(num_features=5)

In [3]:
output = model(features)

print(output.shape)  
print(output)

torch.Size([10, 1])
tensor([[0.6024],
        [0.6069],
        [0.5774],
        [0.5562],
        [0.5782],
        [0.6108],
        [0.5746],
        [0.5982],
        [0.5874],
        [0.5990]], grad_fn=<SigmoidBackward0>)


In [9]:
model.network[0].weight.data, model.network[0].bias.data

(tensor([[-0.0748, -0.1836, -0.1004,  0.0459,  0.1908],
         [ 0.3217,  0.1580,  0.1768,  0.4234,  0.1550],
         [ 0.1172,  0.3009,  0.1491, -0.0119,  0.1371]]),
 tensor([-0.1564,  0.1785,  0.1922]))